/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_AllocationAndRetentionPriority_H_
#define	_AllocationAndRetentionPriority_H_


#include <asn_application.h>



#include "PriorityLevelARP.h"
#include "Pre-emptionCapability.h"
#include "Pre-emptionVulnerability.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct AllocationAndRetentionPriority {
	PriorityLevelARP_t	 priorityLevelARP;
	Pre_emptionCapability_t	 pre_emptionCapability;
	Pre_emptionVulnerability_t	 pre_emptionVulnerability;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} AllocationAndRetentionPriority_t;



extern asn_TYPE_descriptor_t asn_DEF_AllocationAndRetentionPriority;
extern asn_SEQUENCE_specifics_t asn_SPC_AllocationAndRetentionPriority_specs_1;
extern asn_TYPE_member_t asn_MBR_AllocationAndRetentionPriority_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
