/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_AMFPagingTarget_H_
#define	_AMFPagingTarget_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum AMFPagingTarget_PR {
	AMFPagingTarget_PR_NOTHING,	

	AMFPagingTarget_PR_globalRANNodeID,
	AMFPagingTarget_PR_tAI,
	AMFPagingTarget_PR_choice_Extensions
} AMFPagingTarget_PR;



struct GlobalRANNodeID;
struct TAI;
struct ProtocolIE_SingleContainer;



typedef struct AMFPagingTarget {
	AMFPagingTarget_PR present;
	union AMFPagingTarget_u {
		struct GlobalRANNodeID	*globalRANNodeID;
		struct TAI	*tAI;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} AMFPagingTarget_t;



extern asn_TYPE_descriptor_t asn_DEF_AMFPagingTarget;
extern asn_CHOICE_specifics_t asn_SPC_AMFPagingTarget_specs_1;
extern asn_TYPE_member_t asn_MBR_AMFPagingTarget_1[3];
extern asn_per_constraints_t asn_PER_type_AMFPagingTarget_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
