/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_AreaOfInterest_H_
#define	_AreaOfInterest_H_


#include <asn_application.h>



#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct AreaOfInterestTAIList;
struct AreaOfInterestCellList;
struct AreaOfInterestRANNodeList;
struct ProtocolExtensionContainer;



typedef struct AreaOfInterest {
	struct AreaOfInterestTAIList	*areaOfInterestTAIList;	

	struct AreaOfInterestCellList	*areaOfInterestCellList;	

	struct AreaOfInterestRANNodeList	*areaOfInterestRANNodeList;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} AreaOfInterest_t;



extern asn_TYPE_descriptor_t asn_DEF_AreaOfInterest;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaOfInterest_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaOfInterest_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
