/*
 * Generated by asn1c-0.9.29 (http:
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_ProcedureCode (0)
#define max_val_ProcedureCode (255)
#define min_val_ProtocolExtensionID (0)
#define max_val_ProtocolExtensionID (65535)
#define min_val_ProtocolIE_ID (0)
#define max_val_ProtocolIE_ID (65535)
#define maxPrivateIEs (65535)
#define maxProtocolExtensions (65535)
#define maxProtocolIEs (65535)
#define maxnoofAllowedAreas (16)
#define maxnoofAllowedS_NSSAIs (8)
#define maxnoofBPLMNs (12)
#define maxnoofCellIDforWarning (65535)
#define maxnoofCellinAoI (256)
#define maxnoofCellinEAI (65535)
#define maxnoofCellinTAI (65535)
#define maxnoofCellsingNB (16384)
#define maxnoofCellsinngeNB (256)
#define maxnoofCellsinUEHistoryInfo (16)
#define maxnoofCellsUEMovingTrajectory (16)
#define maxnoofDRBs (32)
#define maxnoofEmergencyAreaID (65535)
#define maxnoofEAIforRestart (256)
#define maxnoofEPLMNs (15)
#define maxnoofEPLMNsPlusOne (16)
#define maxnoofE_RABs (256)
#define maxnoofErrors (256)
#define maxnoofForbTACs (4096)
#define maxnoofMultiConnectivities (4)
#define maxnoofNGConnectionsToReset (65536)
#define maxnoofPDUSessions (256)
#define maxnoofPLMNs (12)
#define maxnoofQosFlows (64)
#define maxnoofRANNodeinAoI (64)
#define maxnoofRecommendedCells (16)
#define maxnoofRecommendedRANNodes (16)
#define maxnoofAoI (64)
#define maxnoofServedGUAMIs (256)
#define maxnoofSliceItems (1024)
#define maxnoofTACs (256)
#define maxnoofTAIforInactive (16)
#define maxnoofTAIforPaging (16)
#define maxnoofTAIforRestart (2048)
#define maxnoofTAIforWarning (65535)
#define maxnoofTAIinAoI (16)
#define maxnoofTNLAssociations (32)
#define maxnoofXnExtTLAs (2)
#define maxnoofXnGTP_TLAs (16)
#define maxnoofXnTLAs (16)
#define min_val_AMF_UE_NGAP_ID (0)
#define max_val_AMF_UE_NGAP_ID (1099511627775)
#define min_val_NextHopChainingCount (0)
#define max_val_NextHopChainingCount (7)
#define min_val_NumberOfBroadcasts (0)
#define max_val_NumberOfBroadcasts (65535)
#define min_val_NumberOfBroadcastsRequested (0)
#define max_val_NumberOfBroadcastsRequested (65535)
#define min_val_PDUSessionID (0)
#define max_val_PDUSessionID (255)
#define min_val_PriorityLevelARP (1)
#define max_val_PriorityLevelARP (15)
#define min_val_RANPagingPriority (1)
#define max_val_RANPagingPriority (256)
#define min_val_RAN_UE_NGAP_ID (0)
#define max_val_RAN_UE_NGAP_ID (4294967295)
#define min_val_RelativeAMFCapacity (0)
#define max_val_RelativeAMFCapacity (255)
#define min_val_RepetitionPeriod (0)
#define max_val_RepetitionPeriod (131071)
#define min_val_TimeUEStayedInCell (0)
#define max_val_TimeUEStayedInCell (4095)
#define min_val_TimeUEStayedInCellEnhancedGranularity (0)
#define max_val_TimeUEStayedInCellEnhancedGranularity (40950)
#define min_val_TNLAddressWeightFactor (0)
#define max_val_TNLAddressWeightFactor (255)
#define min_val_TrafficLoadReductionIndication (1)
#define max_val_TrafficLoadReductionIndication (99)


#ifdef __cplusplus
}
#endif

#endif 

