/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_AssociatedQosFlowItem_H_
#define	_AssociatedQosFlowItem_H_


#include <asn_application.h>



#include "QosFlowIdentifier.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum AssociatedQosFlowItem__qosFlowMappingIndication {
	AssociatedQosFlowItem__qosFlowMappingIndication_ul	= 0,
	AssociatedQosFlowItem__qosFlowMappingIndication_dl	= 1
	/*
	 * Enumeration is extensible
	 */
} e_AssociatedQosFlowItem__qosFlowMappingIndication;



struct ProtocolExtensionContainer;



typedef struct AssociatedQosFlowItem {
	QosFlowIdentifier_t	 qosFlowIdentifier;
	long	*qosFlowMappingIndication;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} AssociatedQosFlowItem_t;





extern asn_TYPE_descriptor_t asn_DEF_AssociatedQosFlowItem;
extern asn_SEQUENCE_specifics_t asn_SPC_AssociatedQosFlowItem_specs_1;
extern asn_TYPE_member_t asn_MBR_AssociatedQosFlowItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
