/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_BitRate_H_
#define	_BitRate_H_


#include <asn_application.h>



#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef INTEGER_t	 BitRate_t;



extern asn_per_constraints_t asn_PER_type_BitRate_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BitRate;
asn_struct_free_f BitRate_free;
asn_struct_print_f BitRate_print;
asn_constr_check_f BitRate_constraint;
ber_type_decoder_f BitRate_decode_ber;
der_type_encoder_f BitRate_encode_der;
xer_type_decoder_f BitRate_decode_xer;
xer_type_encoder_f BitRate_encode_xer;
oer_type_decoder_f BitRate_decode_oer;
oer_type_encoder_f BitRate_encode_oer;
per_type_decoder_f BitRate_decode_uper;
per_type_encoder_f BitRate_encode_uper;
per_type_decoder_f BitRate_decode_aper;
per_type_encoder_f BitRate_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
