/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_BroadcastCompletedAreaList_H_
#define	_BroadcastCompletedAreaList_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum BroadcastCompletedAreaList_PR {
	BroadcastCompletedAreaList_PR_NOTHING,	

	BroadcastCompletedAreaList_PR_cellIDBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_tAIBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_cellIDBroadcastNR,
	BroadcastCompletedAreaList_PR_tAIBroadcastNR,
	BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastNR,
	BroadcastCompletedAreaList_PR_choice_Extensions
} BroadcastCompletedAreaList_PR;



struct CellIDBroadcastEUTRA;
struct TAIBroadcastEUTRA;
struct EmergencyAreaIDBroadcastEUTRA;
struct CellIDBroadcastNR;
struct TAIBroadcastNR;
struct EmergencyAreaIDBroadcastNR;
struct ProtocolIE_SingleContainer;



typedef struct BroadcastCompletedAreaList {
	BroadcastCompletedAreaList_PR present;
	union BroadcastCompletedAreaList_u {
		struct CellIDBroadcastEUTRA	*cellIDBroadcastEUTRA;
		struct TAIBroadcastEUTRA	*tAIBroadcastEUTRA;
		struct EmergencyAreaIDBroadcastEUTRA	*emergencyAreaIDBroadcastEUTRA;
		struct CellIDBroadcastNR	*cellIDBroadcastNR;
		struct TAIBroadcastNR	*tAIBroadcastNR;
		struct EmergencyAreaIDBroadcastNR	*emergencyAreaIDBroadcastNR;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} BroadcastCompletedAreaList_t;



extern asn_TYPE_descriptor_t asn_DEF_BroadcastCompletedAreaList;
extern asn_CHOICE_specifics_t asn_SPC_BroadcastCompletedAreaList_specs_1;
extern asn_TYPE_member_t asn_MBR_BroadcastCompletedAreaList_1[7];
extern asn_per_constraints_t asn_PER_type_BroadcastCompletedAreaList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
