/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CancelledCellsInEAI_NR_H_
#define	_CancelledCellsInEAI_NR_H_


#include <asn_application.h>



#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif



struct CancelledCellsInEAI_NR_Item;



typedef struct CancelledCellsInEAI_NR {
	A_SEQUENCE_OF(struct CancelledCellsInEAI_NR_Item) list;
	
	

	asn_struct_ctx_t _asn_ctx;
} CancelledCellsInEAI_NR_t;



extern asn_TYPE_descriptor_t asn_DEF_CancelledCellsInEAI_NR;
extern asn_SET_OF_specifics_t asn_SPC_CancelledCellsInEAI_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_CancelledCellsInEAI_NR_1[1];
extern asn_per_constraints_t asn_PER_type_CancelledCellsInEAI_NR_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
