/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CellIDCancelledNR_Item_H_
#define	_CellIDCancelledNR_Item_H_


#include <asn_application.h>



#include "NR-CGI.h"
#include "NumberOfBroadcasts.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct CellIDCancelledNR_Item {
	NR_CGI_t	 nR_CGI;
	NumberOfBroadcasts_t	 numberOfBroadcasts;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} CellIDCancelledNR_Item_t;



extern asn_TYPE_descriptor_t asn_DEF_CellIDCancelledNR_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_CellIDCancelledNR_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_CellIDCancelledNR_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
