/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CompletedCellsInEAI_EUTRA_H_
#define	_CompletedCellsInEAI_EUTRA_H_


#include <asn_application.h>



#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif



struct CompletedCellsInEAI_EUTRA_Item;



typedef struct CompletedCellsInEAI_EUTRA {
	A_SEQUENCE_OF(struct CompletedCellsInEAI_EUTRA_Item) list;
	
	

	asn_struct_ctx_t _asn_ctx;
} CompletedCellsInEAI_EUTRA_t;



extern asn_TYPE_descriptor_t asn_DEF_CompletedCellsInEAI_EUTRA;
extern asn_SET_OF_specifics_t asn_SPC_CompletedCellsInEAI_EUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_CompletedCellsInEAI_EUTRA_1[1];
extern asn_per_constraints_t asn_PER_type_CompletedCellsInEAI_EUTRA_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
