/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CoreNetworkAssistanceInformation_H_
#define	_CoreNetworkAssistanceInformation_H_


#include <asn_application.h>



#include "UEIdentityIndexValue.h"
#include "PagingDRX.h"
#include "PeriodicRegistrationUpdateTimer.h"
#include "MICOModeIndication.h"
#include "TAIListForInactive.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ExpectedUEBehaviour;
struct ProtocolExtensionContainer;



typedef struct CoreNetworkAssistanceInformation {
	UEIdentityIndexValue_t	 uEIdentityIndexValue;
	PagingDRX_t	*uESpecificDRX;	

	PeriodicRegistrationUpdateTimer_t	 periodicRegistrationUpdateTimer;
	MICOModeIndication_t	*mICOModeIndication;	

	TAIListForInactive_t	 tAIListForInactive;
	struct ExpectedUEBehaviour	*expectedUEBehaviour;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} CoreNetworkAssistanceInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_CoreNetworkAssistanceInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_CoreNetworkAssistanceInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_CoreNetworkAssistanceInformation_1[7];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
