/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CPTransportLayerInformation_H_
#define	_CPTransportLayerInformation_H_


#include <asn_application.h>



#include "TransportLayerAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum CPTransportLayerInformation_PR {
	CPTransportLayerInformation_PR_NOTHING,	

	CPTransportLayerInformation_PR_endpointIPAddress,
	CPTransportLayerInformation_PR_choice_Extensions
} CPTransportLayerInformation_PR;



struct ProtocolIE_SingleContainer;



typedef struct CPTransportLayerInformation {
	CPTransportLayerInformation_PR present;
	union CPTransportLayerInformation_u {
		TransportLayerAddress_t	 endpointIPAddress;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} CPTransportLayerInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_CPTransportLayerInformation;
extern asn_CHOICE_specifics_t asn_SPC_CPTransportLayerInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_CPTransportLayerInformation_1[2];
extern asn_per_constraints_t asn_PER_type_CPTransportLayerInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
