/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_CriticalityDiagnostics_H_
#define	_CriticalityDiagnostics_H_


#include <asn_application.h>



#include "ProcedureCode.h"
#include "TriggeringMessage.h"
#include "Criticality.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct CriticalityDiagnostics_IE_List;
struct ProtocolExtensionContainer;



typedef struct CriticalityDiagnostics {
	ProcedureCode_t	*procedureCode;	

	TriggeringMessage_t	*triggeringMessage;	

	Criticality_t	*procedureCriticality;	

	struct CriticalityDiagnostics_IE_List	*iEsCriticalityDiagnostics;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} CriticalityDiagnostics_t;



extern asn_TYPE_descriptor_t asn_DEF_CriticalityDiagnostics;
extern asn_SEQUENCE_specifics_t asn_SPC_CriticalityDiagnostics_specs_1;
extern asn_TYPE_member_t asn_MBR_CriticalityDiagnostics_1[5];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
