/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_DirectForwardingPathAvailability_H_
#define	_DirectForwardingPathAvailability_H_


#include <asn_application.h>



#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum DirectForwardingPathAvailability {
	DirectForwardingPathAvailability_direct_path_available	= 0
	/*
	 * Enumeration is extensible
	 */
} e_DirectForwardingPathAvailability;



typedef long	 DirectForwardingPathAvailability_t;



extern asn_per_constraints_t asn_PER_type_DirectForwardingPathAvailability_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DirectForwardingPathAvailability;
extern const asn_INTEGER_specifics_t asn_SPC_DirectForwardingPathAvailability_specs_1;
asn_struct_free_f DirectForwardingPathAvailability_free;
asn_struct_print_f DirectForwardingPathAvailability_print;
asn_constr_check_f DirectForwardingPathAvailability_constraint;
ber_type_decoder_f DirectForwardingPathAvailability_decode_ber;
der_type_encoder_f DirectForwardingPathAvailability_encode_der;
xer_type_decoder_f DirectForwardingPathAvailability_decode_xer;
xer_type_encoder_f DirectForwardingPathAvailability_encode_xer;
oer_type_decoder_f DirectForwardingPathAvailability_decode_oer;
oer_type_encoder_f DirectForwardingPathAvailability_encode_oer;
per_type_decoder_f DirectForwardingPathAvailability_decode_uper;
per_type_encoder_f DirectForwardingPathAvailability_encode_uper;
per_type_decoder_f DirectForwardingPathAvailability_decode_aper;
per_type_encoder_f DirectForwardingPathAvailability_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
