/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_DRBStatusDL12_H_
#define	_DRBStatusDL12_H_


#include <asn_application.h>



#include "COUNTValueForPDCP-SN12.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct DRBStatusDL12 {
	COUNTValueForPDCP_SN12_t	 dL_COUNTValue;
	struct ProtocolExtensionContainer	*iE_Extension;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} DRBStatusDL12_t;



extern asn_TYPE_descriptor_t asn_DEF_DRBStatusDL12;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBStatusDL12_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBStatusDL12_1[2];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
