/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_DRBsSubjectToStatusTransferItem_H_
#define	_DRBsSubjectToStatusTransferItem_H_


#include <asn_application.h>



#include "DRB-ID.h"
#include "DRBStatusUL.h"
#include "DRBStatusDL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct DRBsSubjectToStatusTransferItem {
	DRB_ID_t	 dRB_ID;
	DRBStatusUL_t	 dRBStatusUL;
	DRBStatusDL_t	 dRBStatusDL;
	struct ProtocolExtensionContainer	*iE_Extension;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} DRBsSubjectToStatusTransferItem_t;



extern asn_TYPE_descriptor_t asn_DEF_DRBsSubjectToStatusTransferItem;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBsSubjectToStatusTransferItem_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsSubjectToStatusTransferItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
