/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_DRBStatusUL_H_
#define	_DRBStatusUL_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum DRBStatusUL_PR {
	DRBStatusUL_PR_NOTHING,	

	DRBStatusUL_PR_dRBStatusUL12,
	DRBStatusUL_PR_dRBStatusUL18,
	DRBStatusUL_PR_choice_Extensions
} DRBStatusUL_PR;



struct DRBStatusUL12;
struct DRBStatusUL18;
struct ProtocolIE_SingleContainer;



typedef struct DRBStatusUL {
	DRBStatusUL_PR present;
	union DRBStatusUL_u {
		struct DRBStatusUL12	*dRBStatusUL12;
		struct DRBStatusUL18	*dRBStatusUL18;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} DRBStatusUL_t;



extern asn_TYPE_descriptor_t asn_DEF_DRBStatusUL;
extern asn_CHOICE_specifics_t asn_SPC_DRBStatusUL_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBStatusUL_1[3];
extern asn_per_constraints_t asn_PER_type_DRBStatusUL_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
