/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_Dynamic5QIDescriptor_H_
#define	_Dynamic5QIDescriptor_H_


#include <asn_application.h>



#include "PriorityLevelQos.h"
#include "PacketDelayBudget.h"
#include "PacketErrorRate.h"
#include "FiveQI.h"
#include "DelayCritical.h"
#include "AveragingWindow.h"
#include "MaximumDataBurstVolume.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct Dynamic5QIDescriptor {
	PriorityLevelQos_t	 priorityLevelQos;
	PacketDelayBudget_t	 packetDelayBudget;
	PacketErrorRate_t	 packetErrorRate;
	FiveQI_t	*fiveQI;	

	DelayCritical_t	*delayCritical;	

	AveragingWindow_t	*averagingWindow;	

	MaximumDataBurstVolume_t	*maximumDataBurstVolume;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} Dynamic5QIDescriptor_t;



extern asn_TYPE_descriptor_t asn_DEF_Dynamic5QIDescriptor;
extern asn_SEQUENCE_specifics_t asn_SPC_Dynamic5QIDescriptor_specs_1;
extern asn_TYPE_member_t asn_MBR_Dynamic5QIDescriptor_1[8];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
