/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_E_RABInformationList_H_
#define	_E_RABInformationList_H_


#include <asn_application.h>



#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif



struct E_RABInformationItem;



typedef struct E_RABInformationList {
	A_SEQUENCE_OF(struct E_RABInformationItem) list;
	
	

	asn_struct_ctx_t _asn_ctx;
} E_RABInformationList_t;



extern asn_TYPE_descriptor_t asn_DEF_E_RABInformationList;
extern asn_SET_OF_specifics_t asn_SPC_E_RABInformationList_specs_1;
extern asn_TYPE_member_t asn_MBR_E_RABInformationList_1[1];
extern asn_per_constraints_t asn_PER_type_E_RABInformationList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
