/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_E_RAB_ID_H_
#define	_E_RAB_ID_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 E_RAB_ID_t;



extern asn_per_constraints_t asn_PER_type_E_RAB_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_RAB_ID;
asn_struct_free_f E_RAB_ID_free;
asn_struct_print_f E_RAB_ID_print;
asn_constr_check_f E_RAB_ID_constraint;
ber_type_decoder_f E_RAB_ID_decode_ber;
der_type_encoder_f E_RAB_ID_encode_der;
xer_type_decoder_f E_RAB_ID_decode_xer;
xer_type_encoder_f E_RAB_ID_encode_xer;
oer_type_decoder_f E_RAB_ID_decode_oer;
oer_type_encoder_f E_RAB_ID_encode_oer;
per_type_decoder_f E_RAB_ID_decode_uper;
per_type_encoder_f E_RAB_ID_encode_uper;
per_type_decoder_f E_RAB_ID_decode_aper;
per_type_encoder_f E_RAB_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
