/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_EmergencyAreaID_H_
#define	_EmergencyAreaID_H_


#include <asn_application.h>



#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef OCTET_STRING_t	 EmergencyAreaID_t;



extern asn_per_constraints_t asn_PER_type_EmergencyAreaID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EmergencyAreaID;
asn_struct_free_f EmergencyAreaID_free;
asn_struct_print_f EmergencyAreaID_print;
asn_constr_check_f EmergencyAreaID_constraint;
ber_type_decoder_f EmergencyAreaID_decode_ber;
der_type_encoder_f EmergencyAreaID_encode_der;
xer_type_decoder_f EmergencyAreaID_decode_xer;
xer_type_encoder_f EmergencyAreaID_encode_xer;
oer_type_decoder_f EmergencyAreaID_decode_oer;
oer_type_encoder_f EmergencyAreaID_encode_oer;
per_type_decoder_f EmergencyAreaID_decode_uper;
per_type_encoder_f EmergencyAreaID_encode_uper;
per_type_decoder_f EmergencyAreaID_decode_aper;
per_type_encoder_f EmergencyAreaID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
