/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_EPS_TAC_H_
#define	_EPS_TAC_H_


#include <asn_application.h>



#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef OCTET_STRING_t	 EPS_TAC_t;



extern asn_per_constraints_t asn_PER_type_EPS_TAC_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EPS_TAC;
asn_struct_free_f EPS_TAC_free;
asn_struct_print_f EPS_TAC_print;
asn_constr_check_f EPS_TAC_constraint;
ber_type_decoder_f EPS_TAC_decode_ber;
der_type_encoder_f EPS_TAC_encode_der;
xer_type_decoder_f EPS_TAC_decode_xer;
xer_type_encoder_f EPS_TAC_encode_xer;
oer_type_decoder_f EPS_TAC_decode_oer;
oer_type_encoder_f EPS_TAC_encode_oer;
per_type_decoder_f EPS_TAC_decode_uper;
per_type_encoder_f EPS_TAC_encode_uper;
per_type_decoder_f EPS_TAC_decode_aper;
per_type_encoder_f EPS_TAC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
