/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ExpectedUEActivityBehaviour_H_
#define	_ExpectedUEActivityBehaviour_H_


#include <asn_application.h>



#include "ExpectedActivityPeriod.h"
#include "ExpectedIdlePeriod.h"
#include "SourceOfUEActivityBehaviourInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct ExpectedUEActivityBehaviour {
	ExpectedActivityPeriod_t	*expectedActivityPeriod;	

	ExpectedIdlePeriod_t	*expectedIdlePeriod;	

	SourceOfUEActivityBehaviourInformation_t	*sourceOfUEActivityBehaviourInformation;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} ExpectedUEActivityBehaviour_t;



extern asn_TYPE_descriptor_t asn_DEF_ExpectedUEActivityBehaviour;
extern asn_SEQUENCE_specifics_t asn_SPC_ExpectedUEActivityBehaviour_specs_1;
extern asn_TYPE_member_t asn_MBR_ExpectedUEActivityBehaviour_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
