/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ExpectedUEBehaviour_H_
#define	_ExpectedUEBehaviour_H_


#include <asn_application.h>



#include "ExpectedHOInterval.h"
#include "ExpectedUEMobility.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ExpectedUEActivityBehaviour;
struct ExpectedUEMovingTrajectory;
struct ProtocolExtensionContainer;



typedef struct ExpectedUEBehaviour {
	struct ExpectedUEActivityBehaviour	*expectedUEActivityBehaviour;	

	ExpectedHOInterval_t	*expectedHOInterval;	

	ExpectedUEMobility_t	*expectedUEMobility;	

	struct ExpectedUEMovingTrajectory	*expectedUEMovingTrajectory;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} ExpectedUEBehaviour_t;



extern asn_TYPE_descriptor_t asn_DEF_ExpectedUEBehaviour;
extern asn_SEQUENCE_specifics_t asn_SPC_ExpectedUEBehaviour_specs_1;
extern asn_TYPE_member_t asn_MBR_ExpectedUEBehaviour_1[5];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
