/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ExpectedActivityPeriod_H_
#define	_ExpectedActivityPeriod_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 ExpectedActivityPeriod_t;



extern asn_per_constraints_t asn_PER_type_ExpectedActivityPeriod_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExpectedActivityPeriod;
asn_struct_free_f ExpectedActivityPeriod_free;
asn_struct_print_f ExpectedActivityPeriod_print;
asn_constr_check_f ExpectedActivityPeriod_constraint;
ber_type_decoder_f ExpectedActivityPeriod_decode_ber;
der_type_encoder_f ExpectedActivityPeriod_encode_der;
xer_type_decoder_f ExpectedActivityPeriod_decode_xer;
xer_type_encoder_f ExpectedActivityPeriod_encode_xer;
oer_type_decoder_f ExpectedActivityPeriod_decode_oer;
oer_type_encoder_f ExpectedActivityPeriod_encode_oer;
per_type_decoder_f ExpectedActivityPeriod_decode_uper;
per_type_encoder_f ExpectedActivityPeriod_encode_uper;
per_type_decoder_f ExpectedActivityPeriod_decode_aper;
per_type_encoder_f ExpectedActivityPeriod_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
