/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_FiveG_S_TMSI_H_
#define	_FiveG_S_TMSI_H_


#include <asn_application.h>



#include "AMFSetID.h"
#include "AMFPointer.h"
#include "FiveG-TMSI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct FiveG_S_TMSI {
	AMFSetID_t	 aMFSetID;
	AMFPointer_t	 aMFPointer;
	FiveG_TMSI_t	 fiveG_TMSI;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} FiveG_S_TMSI_t;



extern asn_TYPE_descriptor_t asn_DEF_FiveG_S_TMSI;
extern asn_SEQUENCE_specifics_t asn_SPC_FiveG_S_TMSI_specs_1;
extern asn_TYPE_member_t asn_MBR_FiveG_S_TMSI_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
