/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_GBR_QosInformation_H_
#define	_GBR_QosInformation_H_


#include <asn_application.h>



#include "BitRate.h"
#include "NotificationControl.h"
#include "PacketLossRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct GBR_QosInformation {
	BitRate_t	 maximumFlowBitRateDL;
	BitRate_t	 maximumFlowBitRateUL;
	BitRate_t	 guaranteedFlowBitRateDL;
	BitRate_t	 guaranteedFlowBitRateUL;
	NotificationControl_t	*notificationControl;	

	PacketLossRate_t	*maximumPacketLossRateDL;	

	PacketLossRate_t	*maximumPacketLossRateUL;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} GBR_QosInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_GBR_QosInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_GBR_QosInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_GBR_QosInformation_1[8];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
