/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_GlobalRANNodeID_H_
#define	_GlobalRANNodeID_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum GlobalRANNodeID_PR {
	GlobalRANNodeID_PR_NOTHING,	

	GlobalRANNodeID_PR_globalGNB_ID,
	GlobalRANNodeID_PR_globalNgENB_ID,
	GlobalRANNodeID_PR_globalN3IWF_ID,
	GlobalRANNodeID_PR_choice_Extensions
} GlobalRANNodeID_PR;



struct GlobalGNB_ID;
struct GlobalNgENB_ID;
struct GlobalN3IWF_ID;
struct ProtocolIE_SingleContainer;



typedef struct GlobalRANNodeID {
	GlobalRANNodeID_PR present;
	union GlobalRANNodeID_u {
		struct GlobalGNB_ID	*globalGNB_ID;
		struct GlobalNgENB_ID	*globalNgENB_ID;
		struct GlobalN3IWF_ID	*globalN3IWF_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} GlobalRANNodeID_t;



extern asn_TYPE_descriptor_t asn_DEF_GlobalRANNodeID;
extern asn_CHOICE_specifics_t asn_SPC_GlobalRANNodeID_specs_1;
extern asn_TYPE_member_t asn_MBR_GlobalRANNodeID_1[4];
extern asn_per_constraints_t asn_PER_type_GlobalRANNodeID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
