/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_GTPTunnel_H_
#define	_GTPTunnel_H_


#include <asn_application.h>



#include "TransportLayerAddress.h"
#include "GTP-TEID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct GTPTunnel {
	TransportLayerAddress_t	 transportLayerAddress;
	GTP_TEID_t	 gTP_TEID;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} GTPTunnel_t;



extern asn_TYPE_descriptor_t asn_DEF_GTPTunnel;
extern asn_SEQUENCE_specifics_t asn_SPC_GTPTunnel_specs_1;
extern asn_TYPE_member_t asn_MBR_GTPTunnel_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
