/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_IMSVoiceSupportIndicator_H_
#define	_IMSVoiceSupportIndicator_H_


#include <asn_application.h>



#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum IMSVoiceSupportIndicator {
	IMSVoiceSupportIndicator_supported	= 0,
	IMSVoiceSupportIndicator_not_supported	= 1
	/*
	 * Enumeration is extensible
	 */
} e_IMSVoiceSupportIndicator;



typedef long	 IMSVoiceSupportIndicator_t;



extern asn_per_constraints_t asn_PER_type_IMSVoiceSupportIndicator_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IMSVoiceSupportIndicator;
extern const asn_INTEGER_specifics_t asn_SPC_IMSVoiceSupportIndicator_specs_1;
asn_struct_free_f IMSVoiceSupportIndicator_free;
asn_struct_print_f IMSVoiceSupportIndicator_print;
asn_constr_check_f IMSVoiceSupportIndicator_constraint;
ber_type_decoder_f IMSVoiceSupportIndicator_decode_ber;
der_type_encoder_f IMSVoiceSupportIndicator_encode_der;
xer_type_decoder_f IMSVoiceSupportIndicator_decode_xer;
xer_type_encoder_f IMSVoiceSupportIndicator_encode_xer;
oer_type_decoder_f IMSVoiceSupportIndicator_decode_oer;
oer_type_encoder_f IMSVoiceSupportIndicator_encode_oer;
per_type_decoder_f IMSVoiceSupportIndicator_decode_uper;
per_type_encoder_f IMSVoiceSupportIndicator_encode_uper;
per_type_decoder_f IMSVoiceSupportIndicator_decode_aper;
per_type_encoder_f IMSVoiceSupportIndicator_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
