/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_LastVisitedGERANCellInformation_H_
#define	_LastVisitedGERANCellInformation_H_


#include <asn_application.h>



#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef OCTET_STRING_t	 LastVisitedGERANCellInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_LastVisitedGERANCellInformation;
asn_struct_free_f LastVisitedGERANCellInformation_free;
asn_struct_print_f LastVisitedGERANCellInformation_print;
asn_constr_check_f LastVisitedGERANCellInformation_constraint;
ber_type_decoder_f LastVisitedGERANCellInformation_decode_ber;
der_type_encoder_f LastVisitedGERANCellInformation_encode_der;
xer_type_decoder_f LastVisitedGERANCellInformation_decode_xer;
xer_type_encoder_f LastVisitedGERANCellInformation_encode_xer;
oer_type_decoder_f LastVisitedGERANCellInformation_decode_oer;
oer_type_encoder_f LastVisitedGERANCellInformation_encode_oer;
per_type_decoder_f LastVisitedGERANCellInformation_decode_uper;
per_type_encoder_f LastVisitedGERANCellInformation_encode_uper;
per_type_decoder_f LastVisitedGERANCellInformation_decode_aper;
per_type_encoder_f LastVisitedGERANCellInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
