/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_LastVisitedNGRANCellInformation_H_
#define	_LastVisitedNGRANCellInformation_H_


#include <asn_application.h>



#include "NGRAN-CGI.h"
#include "CellType.h"
#include "TimeUEStayedInCell.h"
#include "TimeUEStayedInCellEnhancedGranularity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct Cause;
struct ProtocolExtensionContainer;



typedef struct LastVisitedNGRANCellInformation {
	NGRAN_CGI_t	 globalCellID;
	CellType_t	 cellType;
	TimeUEStayedInCell_t	 timeUEStayedInCell;
	TimeUEStayedInCellEnhancedGranularity_t	*timeUEStayedInCellEnhancedGranularity;	

	struct Cause	*hOCauseValue;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} LastVisitedNGRANCellInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_LastVisitedNGRANCellInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_LastVisitedNGRANCellInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_LastVisitedNGRANCellInformation_1[6];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
