/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_MobilityRestrictionList_H_
#define	_MobilityRestrictionList_H_


#include <asn_application.h>



#include "PLMNIdentity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct EquivalentPLMNs;
struct RATRestrictions;
struct ForbiddenAreaInformation;
struct ServiceAreaInformation;
struct ProtocolExtensionContainer;



typedef struct MobilityRestrictionList {
	PLMNIdentity_t	 servingPLMN;
	struct EquivalentPLMNs	*equivalentPLMNs;	

	struct RATRestrictions	*rATRestrictions;	

	struct ForbiddenAreaInformation	*forbiddenAreaInformation;	

	struct ServiceAreaInformation	*serviceAreaInformation;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} MobilityRestrictionList_t;



extern asn_TYPE_descriptor_t asn_DEF_MobilityRestrictionList;
extern asn_SEQUENCE_specifics_t asn_SPC_MobilityRestrictionList_specs_1;
extern asn_TYPE_member_t asn_MBR_MobilityRestrictionList_1[6];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
