/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NASSecurityParametersFromNGRAN_H_
#define	_NASSecurityParametersFromNGRAN_H_


#include <asn_application.h>



#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef OCTET_STRING_t	 NASSecurityParametersFromNGRAN_t;



extern asn_TYPE_descriptor_t asn_DEF_NASSecurityParametersFromNGRAN;
asn_struct_free_f NASSecurityParametersFromNGRAN_free;
asn_struct_print_f NASSecurityParametersFromNGRAN_print;
asn_constr_check_f NASSecurityParametersFromNGRAN_constraint;
ber_type_decoder_f NASSecurityParametersFromNGRAN_decode_ber;
der_type_encoder_f NASSecurityParametersFromNGRAN_encode_der;
xer_type_decoder_f NASSecurityParametersFromNGRAN_decode_xer;
xer_type_encoder_f NASSecurityParametersFromNGRAN_encode_xer;
oer_type_decoder_f NASSecurityParametersFromNGRAN_decode_oer;
oer_type_encoder_f NASSecurityParametersFromNGRAN_encode_oer;
per_type_decoder_f NASSecurityParametersFromNGRAN_decode_uper;
per_type_encoder_f NASSecurityParametersFromNGRAN_encode_uper;
per_type_decoder_f NASSecurityParametersFromNGRAN_decode_aper;
per_type_encoder_f NASSecurityParametersFromNGRAN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
