/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NetworkInstance_H_
#define	_NetworkInstance_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 NetworkInstance_t;



extern asn_per_constraints_t asn_PER_type_NetworkInstance_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NetworkInstance;
asn_struct_free_f NetworkInstance_free;
asn_struct_print_f NetworkInstance_print;
asn_constr_check_f NetworkInstance_constraint;
ber_type_decoder_f NetworkInstance_decode_ber;
der_type_encoder_f NetworkInstance_encode_der;
xer_type_decoder_f NetworkInstance_decode_xer;
xer_type_encoder_f NetworkInstance_encode_xer;
oer_type_decoder_f NetworkInstance_decode_oer;
oer_type_encoder_f NetworkInstance_encode_oer;
per_type_decoder_f NetworkInstance_decode_uper;
per_type_encoder_f NetworkInstance_encode_uper;
per_type_decoder_f NetworkInstance_decode_aper;
per_type_encoder_f NetworkInstance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
