/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-PDU-Descriptions"
 * 	found in "ElementaryProcedureDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NGAP_PDU_H_
#define	_NGAP_PDU_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum NGAP_PDU_PR {
	NGAP_PDU_PR_NOTHING,	

	NGAP_PDU_PR_initiatingMessage,
	NGAP_PDU_PR_successfulOutcome,
	NGAP_PDU_PR_unsuccessfulOutcome
	

	
} NGAP_PDU_PR;



struct InitiatingMessage;
struct SuccessfulOutcome;
struct UnsuccessfulOutcome;



typedef struct NGAP_PDU {
	NGAP_PDU_PR present;
	union NGAP_PDU_u {
		struct InitiatingMessage	*initiatingMessage;
		struct SuccessfulOutcome	*successfulOutcome;
		struct UnsuccessfulOutcome	*unsuccessfulOutcome;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} NGAP_PDU_t;



extern asn_TYPE_descriptor_t asn_DEF_NGAP_PDU;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
