/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NgENB_ID_H_
#define	_NgENB_ID_H_


#include <asn_application.h>



#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum NgENB_ID_PR {
	NgENB_ID_PR_NOTHING,	

	NgENB_ID_PR_macroNgENB_ID,
	NgENB_ID_PR_shortMacroNgENB_ID,
	NgENB_ID_PR_longMacroNgENB_ID,
	NgENB_ID_PR_choice_Extensions
} NgENB_ID_PR;



struct ProtocolIE_SingleContainer;



typedef struct NgENB_ID {
	NgENB_ID_PR present;
	union NgENB_ID_u {
		BIT_STRING_t	 macroNgENB_ID;
		BIT_STRING_t	 shortMacroNgENB_ID;
		BIT_STRING_t	 longMacroNgENB_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} NgENB_ID_t;



extern asn_TYPE_descriptor_t asn_DEF_NgENB_ID;
extern asn_CHOICE_specifics_t asn_SPC_NgENB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_NgENB_ID_1[4];
extern asn_per_constraints_t asn_PER_type_NgENB_ID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
