/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NonDynamic5QIDescriptor_H_
#define	_NonDynamic5QIDescriptor_H_


#include <asn_application.h>



#include "FiveQI.h"
#include "PriorityLevelQos.h"
#include "AveragingWindow.h"
#include "MaximumDataBurstVolume.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct NonDynamic5QIDescriptor {
	FiveQI_t	 fiveQI;
	PriorityLevelQos_t	*priorityLevelQos;	

	AveragingWindow_t	*averagingWindow;	

	MaximumDataBurstVolume_t	*maximumDataBurstVolume;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} NonDynamic5QIDescriptor_t;



extern asn_TYPE_descriptor_t asn_DEF_NonDynamic5QIDescriptor;
extern asn_SEQUENCE_specifics_t asn_SPC_NonDynamic5QIDescriptor_specs_1;
extern asn_TYPE_member_t asn_MBR_NonDynamic5QIDescriptor_1[5];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
