/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_NumberOfBroadcastsRequested_H_
#define	_NumberOfBroadcastsRequested_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 NumberOfBroadcastsRequested_t;



extern asn_per_constraints_t asn_PER_type_NumberOfBroadcastsRequested_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NumberOfBroadcastsRequested;
asn_struct_free_f NumberOfBroadcastsRequested_free;
asn_struct_print_f NumberOfBroadcastsRequested_print;
asn_constr_check_f NumberOfBroadcastsRequested_constraint;
ber_type_decoder_f NumberOfBroadcastsRequested_decode_ber;
der_type_encoder_f NumberOfBroadcastsRequested_encode_der;
xer_type_decoder_f NumberOfBroadcastsRequested_decode_xer;
xer_type_encoder_f NumberOfBroadcastsRequested_encode_xer;
oer_type_decoder_f NumberOfBroadcastsRequested_decode_oer;
oer_type_encoder_f NumberOfBroadcastsRequested_encode_oer;
per_type_decoder_f NumberOfBroadcastsRequested_decode_uper;
per_type_encoder_f NumberOfBroadcastsRequested_encode_uper;
per_type_decoder_f NumberOfBroadcastsRequested_decode_aper;
per_type_encoder_f NumberOfBroadcastsRequested_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
