/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_OverloadStartNSSAIItem_H_
#define	_OverloadStartNSSAIItem_H_


#include <asn_application.h>



#include "SliceOverloadList.h"
#include "TrafficLoadReductionIndication.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct OverloadResponse;
struct ProtocolExtensionContainer;



typedef struct OverloadStartNSSAIItem {
	SliceOverloadList_t	 sliceOverloadList;
	struct OverloadResponse	*sliceOverloadResponse;	

	TrafficLoadReductionIndication_t	*sliceTrafficLoadReductionIndication;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} OverloadStartNSSAIItem_t;



extern asn_TYPE_descriptor_t asn_DEF_OverloadStartNSSAIItem;
extern asn_SEQUENCE_specifics_t asn_SPC_OverloadStartNSSAIItem_specs_1;
extern asn_TYPE_member_t asn_MBR_OverloadStartNSSAIItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
