/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_OverloadResponse_H_
#define	_OverloadResponse_H_


#include <asn_application.h>



#include "OverloadAction.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum OverloadResponse_PR {
	OverloadResponse_PR_NOTHING,	

	OverloadResponse_PR_overloadAction,
	OverloadResponse_PR_choice_Extensions
} OverloadResponse_PR;



struct ProtocolIE_SingleContainer;



typedef struct OverloadResponse {
	OverloadResponse_PR present;
	union OverloadResponse_u {
		OverloadAction_t	 overloadAction;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} OverloadResponse_t;



extern asn_TYPE_descriptor_t asn_DEF_OverloadResponse;
extern asn_CHOICE_specifics_t asn_SPC_OverloadResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_OverloadResponse_1[2];
extern asn_per_constraints_t asn_PER_type_OverloadResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
