/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PathSwitchRequestAcknowledgeTransfer_H_
#define	_PathSwitchRequestAcknowledgeTransfer_H_


#include <asn_application.h>



#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct UPTransportLayerInformation;
struct SecurityIndication;
struct ProtocolExtensionContainer;



typedef struct PathSwitchRequestAcknowledgeTransfer {
	struct UPTransportLayerInformation	*uL_NGU_UP_TNLInformation;	

	struct SecurityIndication	*securityIndication;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} PathSwitchRequestAcknowledgeTransfer_t;



extern asn_TYPE_descriptor_t asn_DEF_PathSwitchRequestAcknowledgeTransfer;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
