/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PathSwitchRequestTransfer_H_
#define	_PathSwitchRequestTransfer_H_


#include <asn_application.h>



#include "UPTransportLayerInformation.h"
#include "DL-NGU-TNLInformationReused.h"
#include "QosFlowAcceptedList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct UserPlaneSecurityInformation;
struct ProtocolExtensionContainer;



typedef struct PathSwitchRequestTransfer {
	UPTransportLayerInformation_t	 dL_NGU_UP_TNLInformation;
	DL_NGU_TNLInformationReused_t	*dL_NGU_TNLInformationReused;	

	struct UserPlaneSecurityInformation	*userPlaneSecurityInformation;	

	QosFlowAcceptedList_t	 qosFlowAcceptedList;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} PathSwitchRequestTransfer_t;



extern asn_TYPE_descriptor_t asn_DEF_PathSwitchRequestTransfer;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
