/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PDUSessionResourceModifyIndicationTransfer_H_
#define	_PDUSessionResourceModifyIndicationTransfer_H_


#include <asn_application.h>



#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct UP_TNLInformation;
struct ProtocolExtensionContainer;



typedef struct PDUSessionResourceModifyIndicationTransfer {
	struct UP_TNLInformation	*dL_UP_TNLInformation;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceModifyIndicationTransfer_t;



extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceModifyIndicationTransfer;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
