/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PDUSessionResourceModifyItemModReq_H_
#define	_PDUSessionResourceModifyItemModReq_H_


#include <asn_application.h>



#include "PDUSessionID.h"
#include "NAS-PDU.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct PDUSessionResourceModifyItemModReq {
	PDUSessionID_t	 pDUSessionID;
	NAS_PDU_t	*nAS_PDU;	

	OCTET_STRING_t	 pDUSessionResourceModifyRequestTransfer;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceModifyItemModReq_t;



extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceModifyItemModReq;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceModifyItemModReq_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceModifyItemModReq_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
