/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-Containers"
 * 	found in "ContainerDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PrivateIE_Container_H_
#define	_PrivateIE_Container_H_


#include <asn_application.h>



#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif



struct PrivateMessageIEs;



typedef struct PrivateIE_Container_191P0 {
	A_SEQUENCE_OF(struct PrivateMessageIEs) list;
	
	

	asn_struct_ctx_t _asn_ctx;
} PrivateIE_Container_191P0_t;



extern asn_TYPE_descriptor_t asn_DEF_PrivateIE_Container_191P0;
extern asn_SET_OF_specifics_t asn_SPC_PrivateIE_Container_191P0_specs_1;
extern asn_TYPE_member_t asn_MBR_PrivateIE_Container_191P0_1[1];
extern asn_per_constraints_t asn_PER_type_PrivateIE_Container_191P0_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
