/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-Containers"
 * 	found in "ContainerDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ProtocolIE_ContainerPair_H_
#define	_ProtocolIE_ContainerPair_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
