/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_PWSFailedCellIDList_H_
#define	_PWSFailedCellIDList_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum PWSFailedCellIDList_PR {
	PWSFailedCellIDList_PR_NOTHING,	

	PWSFailedCellIDList_PR_eUTRA_CGI_PWSFailedList,
	PWSFailedCellIDList_PR_nR_CGI_PWSFailedList,
	PWSFailedCellIDList_PR_choice_Extensions
} PWSFailedCellIDList_PR;



struct EUTRA_CGIList;
struct NR_CGIList;
struct ProtocolIE_SingleContainer;



typedef struct PWSFailedCellIDList {
	PWSFailedCellIDList_PR present;
	union PWSFailedCellIDList_u {
		struct EUTRA_CGIList	*eUTRA_CGI_PWSFailedList;
		struct NR_CGIList	*nR_CGI_PWSFailedList;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} PWSFailedCellIDList_t;



extern asn_TYPE_descriptor_t asn_DEF_PWSFailedCellIDList;
extern asn_CHOICE_specifics_t asn_SPC_PWSFailedCellIDList_specs_1;
extern asn_TYPE_member_t asn_MBR_PWSFailedCellIDList_1[3];
extern asn_per_constraints_t asn_PER_type_PWSFailedCellIDList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
