/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_QosFlowIdentifier_H_
#define	_QosFlowIdentifier_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 QosFlowIdentifier_t;



extern asn_per_constraints_t asn_PER_type_QosFlowIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_QosFlowIdentifier;
asn_struct_free_f QosFlowIdentifier_free;
asn_struct_print_f QosFlowIdentifier_print;
asn_constr_check_f QosFlowIdentifier_constraint;
ber_type_decoder_f QosFlowIdentifier_decode_ber;
der_type_encoder_f QosFlowIdentifier_encode_der;
xer_type_decoder_f QosFlowIdentifier_decode_xer;
xer_type_encoder_f QosFlowIdentifier_encode_xer;
oer_type_decoder_f QosFlowIdentifier_decode_oer;
oer_type_encoder_f QosFlowIdentifier_encode_oer;
per_type_decoder_f QosFlowIdentifier_decode_uper;
per_type_encoder_f QosFlowIdentifier_encode_uper;
per_type_decoder_f QosFlowIdentifier_decode_aper;
per_type_encoder_f QosFlowIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
