/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_QosFlowLevelQosParameters_H_
#define	_QosFlowLevelQosParameters_H_


#include <asn_application.h>



#include "QosCharacteristics.h"
#include "AllocationAndRetentionPriority.h"
#include "GBR-QosInformation.h"
#include "ReflectiveQosAttribute.h"
#include "AdditionalQosFlowInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct GBR_QosInformation;
struct ProtocolExtensionContainer;



typedef struct QosFlowLevelQosParameters {
	QosCharacteristics_t	 qosCharacteristics;
	AllocationAndRetentionPriority_t	 allocationAndRetentionPriority;
	struct GBR_QosInformation	*gBR_QosInformation;	

	ReflectiveQosAttribute_t	*reflectiveQosAttribute;	

	AdditionalQosFlowInformation_t	*additionalQosFlowInformation;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} QosFlowLevelQosParameters_t;



extern asn_TYPE_descriptor_t asn_DEF_QosFlowLevelQosParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_QosFlowLevelQosParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowLevelQosParameters_1[6];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
