/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_QosFlowAddOrModifyRequestItem_H_
#define	_QosFlowAddOrModifyRequestItem_H_


#include <asn_application.h>



#include "QosFlowIdentifier.h"
#include "E-RAB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct QosFlowLevelQosParameters;
struct ProtocolExtensionContainer;



typedef struct QosFlowAddOrModifyRequestItem {
	QosFlowIdentifier_t	 qosFlowIdentifier;
	struct QosFlowLevelQosParameters	*qosFlowLevelQosParameters;	

	E_RAB_ID_t	*e_RAB_ID;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} QosFlowAddOrModifyRequestItem_t;



extern asn_TYPE_descriptor_t asn_DEF_QosFlowAddOrModifyRequestItem;
extern asn_SEQUENCE_specifics_t asn_SPC_QosFlowAddOrModifyRequestItem_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowAddOrModifyRequestItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
