/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_QosFlowSetupResponseListSURes_H_
#define	_QosFlowSetupResponseListSURes_H_


#include <asn_application.h>



#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif



struct QosFlowSetupResponseItemSURes;



typedef struct QosFlowSetupResponseListSURes {
	A_SEQUENCE_OF(struct QosFlowSetupResponseItemSURes) list;
	
	

	asn_struct_ctx_t _asn_ctx;
} QosFlowSetupResponseListSURes_t;



extern asn_TYPE_descriptor_t asn_DEF_QosFlowSetupResponseListSURes;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
