/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_RecommendedCellItem_H_
#define	_RecommendedCellItem_H_


#include <asn_application.h>



#include "NGRAN-CGI.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct RecommendedCellItem {
	NGRAN_CGI_t	 nGRAN_CGI;
	long	*timeStayedInCell;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} RecommendedCellItem_t;



extern asn_TYPE_descriptor_t asn_DEF_RecommendedCellItem;
extern asn_SEQUENCE_specifics_t asn_SPC_RecommendedCellItem_specs_1;
extern asn_TYPE_member_t asn_MBR_RecommendedCellItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
