/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ReferenceID_H_
#define	_ReferenceID_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 ReferenceID_t;



extern asn_TYPE_descriptor_t asn_DEF_ReferenceID;
asn_struct_free_f ReferenceID_free;
asn_struct_print_f ReferenceID_print;
asn_constr_check_f ReferenceID_constraint;
ber_type_decoder_f ReferenceID_decode_ber;
der_type_encoder_f ReferenceID_encode_der;
xer_type_decoder_f ReferenceID_decode_xer;
xer_type_encoder_f ReferenceID_encode_xer;
oer_type_decoder_f ReferenceID_decode_oer;
oer_type_encoder_f ReferenceID_encode_oer;
per_type_decoder_f ReferenceID_decode_uper;
per_type_encoder_f ReferenceID_encode_uper;
per_type_decoder_f ReferenceID_decode_aper;
per_type_encoder_f ReferenceID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
