/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ReflectiveQosAttribute_H_
#define	_ReflectiveQosAttribute_H_


#include <asn_application.h>



#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum ReflectiveQosAttribute {
	ReflectiveQosAttribute_subject_to	= 0
	/*
	 * Enumeration is extensible
	 */
} e_ReflectiveQosAttribute;



typedef long	 ReflectiveQosAttribute_t;



extern asn_per_constraints_t asn_PER_type_ReflectiveQosAttribute_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ReflectiveQosAttribute;
extern const asn_INTEGER_specifics_t asn_SPC_ReflectiveQosAttribute_specs_1;
asn_struct_free_f ReflectiveQosAttribute_free;
asn_struct_print_f ReflectiveQosAttribute_print;
asn_constr_check_f ReflectiveQosAttribute_constraint;
ber_type_decoder_f ReflectiveQosAttribute_decode_ber;
der_type_encoder_f ReflectiveQosAttribute_encode_der;
xer_type_decoder_f ReflectiveQosAttribute_decode_xer;
xer_type_encoder_f ReflectiveQosAttribute_encode_xer;
oer_type_decoder_f ReflectiveQosAttribute_decode_oer;
oer_type_encoder_f ReflectiveQosAttribute_encode_oer;
per_type_decoder_f ReflectiveQosAttribute_decode_uper;
per_type_encoder_f ReflectiveQosAttribute_encode_uper;
per_type_decoder_f ReflectiveQosAttribute_decode_aper;
per_type_encoder_f ReflectiveQosAttribute_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
