/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_ResetAll_H_
#define	_ResetAll_H_


#include <asn_application.h>



#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum ResetAll {
	ResetAll_reset_all	= 0
	/*
	 * Enumeration is extensible
	 */
} e_ResetAll;



typedef long	 ResetAll_t;



extern asn_per_constraints_t asn_PER_type_ResetAll_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ResetAll;
extern const asn_INTEGER_specifics_t asn_SPC_ResetAll_specs_1;
asn_struct_free_f ResetAll_free;
asn_struct_print_f ResetAll_print;
asn_constr_check_f ResetAll_constraint;
ber_type_decoder_f ResetAll_decode_ber;
der_type_encoder_f ResetAll_encode_der;
xer_type_decoder_f ResetAll_decode_xer;
xer_type_encoder_f ResetAll_encode_xer;
oer_type_decoder_f ResetAll_decode_oer;
oer_type_encoder_f ResetAll_encode_oer;
per_type_decoder_f ResetAll_decode_uper;
per_type_encoder_f ResetAll_encode_uper;
per_type_decoder_f ResetAll_decode_aper;
per_type_encoder_f ResetAll_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
