/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_RRCContainer_H_
#define	_RRCContainer_H_


#include <asn_application.h>



#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef OCTET_STRING_t	 RRCContainer_t;



extern asn_TYPE_descriptor_t asn_DEF_RRCContainer;
asn_struct_free_f RRCContainer_free;
asn_struct_print_f RRCContainer_print;
asn_constr_check_f RRCContainer_constraint;
ber_type_decoder_f RRCContainer_decode_ber;
der_type_encoder_f RRCContainer_encode_der;
xer_type_decoder_f RRCContainer_decode_xer;
xer_type_encoder_f RRCContainer_encode_xer;
oer_type_decoder_f RRCContainer_decode_oer;
oer_type_encoder_f RRCContainer_encode_oer;
per_type_decoder_f RRCContainer_decode_uper;
per_type_encoder_f RRCContainer_encode_uper;
per_type_decoder_f RRCContainer_decode_aper;
per_type_encoder_f RRCContainer_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
