/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_S_NSSAI_H_
#define	_S_NSSAI_H_


#include <asn_application.h>



#include "SST.h"
#include "SD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct S_NSSAI {
	SST_t	 sST;
	SD_t	*sD;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} S_NSSAI_t;



extern asn_TYPE_descriptor_t asn_DEF_S_NSSAI;
extern asn_SEQUENCE_specifics_t asn_SPC_S_NSSAI_specs_1;
extern asn_TYPE_member_t asn_MBR_S_NSSAI_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
