/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SecurityIndication_H_
#define	_SecurityIndication_H_


#include <asn_application.h>



#include "IntegrityProtectionIndication.h"
#include "ConfidentialityProtectionIndication.h"
#include "MaximumIntegrityProtectedDataRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct SecurityIndication {
	IntegrityProtectionIndication_t	 integrityProtectionIndication;
	ConfidentialityProtectionIndication_t	 confidentialityProtectionIndication;
	MaximumIntegrityProtectedDataRate_t	*maximumIntegrityProtectedDataRate;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} SecurityIndication_t;



extern asn_TYPE_descriptor_t asn_DEF_SecurityIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityIndication_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
