/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SerialNumber_H_
#define	_SerialNumber_H_


#include <asn_application.h>



#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef BIT_STRING_t	 SerialNumber_t;



extern asn_per_constraints_t asn_PER_type_SerialNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SerialNumber;
asn_struct_free_f SerialNumber_free;
asn_struct_print_f SerialNumber_print;
asn_constr_check_f SerialNumber_constraint;
ber_type_decoder_f SerialNumber_decode_ber;
der_type_encoder_f SerialNumber_encode_der;
xer_type_decoder_f SerialNumber_decode_xer;
xer_type_encoder_f SerialNumber_encode_xer;
oer_type_decoder_f SerialNumber_decode_oer;
oer_type_encoder_f SerialNumber_encode_oer;
per_type_decoder_f SerialNumber_decode_uper;
per_type_encoder_f SerialNumber_encode_uper;
per_type_decoder_f SerialNumber_decode_aper;
per_type_encoder_f SerialNumber_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
