/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SONConfigurationTransfer_H_
#define	_SONConfigurationTransfer_H_


#include <asn_application.h>



#include "TargetRANNodeID.h"
#include "SourceRANNodeID.h"
#include "SONInformation.h"
#include "XnTNLConfigurationInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct SONConfigurationTransfer {
	TargetRANNodeID_t	 targetRANNodeID;
	SourceRANNodeID_t	 sourceRANNodeID;
	SONInformation_t	 sONInformation;
	XnTNLConfigurationInfo_t	 xnTNLConfigurationInfo;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} SONConfigurationTransfer_t;



extern asn_TYPE_descriptor_t asn_DEF_SONConfigurationTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_SONConfigurationTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_SONConfigurationTransfer_1[5];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
