/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_SourceOfUEActivityBehaviourInformation_H_
#define	_SourceOfUEActivityBehaviourInformation_H_


#include <asn_application.h>



#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum SourceOfUEActivityBehaviourInformation {
	SourceOfUEActivityBehaviourInformation_subscription_information	= 0,
	SourceOfUEActivityBehaviourInformation_statistics	= 1
	/*
	 * Enumeration is extensible
	 */
} e_SourceOfUEActivityBehaviourInformation;



typedef long	 SourceOfUEActivityBehaviourInformation_t;



extern asn_per_constraints_t asn_PER_type_SourceOfUEActivityBehaviourInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SourceOfUEActivityBehaviourInformation;
extern const asn_INTEGER_specifics_t asn_SPC_SourceOfUEActivityBehaviourInformation_specs_1;
asn_struct_free_f SourceOfUEActivityBehaviourInformation_free;
asn_struct_print_f SourceOfUEActivityBehaviourInformation_print;
asn_constr_check_f SourceOfUEActivityBehaviourInformation_constraint;
ber_type_decoder_f SourceOfUEActivityBehaviourInformation_decode_ber;
der_type_encoder_f SourceOfUEActivityBehaviourInformation_encode_der;
xer_type_decoder_f SourceOfUEActivityBehaviourInformation_decode_xer;
xer_type_encoder_f SourceOfUEActivityBehaviourInformation_encode_xer;
oer_type_decoder_f SourceOfUEActivityBehaviourInformation_decode_oer;
oer_type_encoder_f SourceOfUEActivityBehaviourInformation_encode_oer;
per_type_decoder_f SourceOfUEActivityBehaviourInformation_decode_uper;
per_type_encoder_f SourceOfUEActivityBehaviourInformation_encode_uper;
per_type_decoder_f SourceOfUEActivityBehaviourInformation_decode_aper;
per_type_encoder_f SourceOfUEActivityBehaviourInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
