/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_TargetID_H_
#define	_TargetID_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum TargetID_PR {
	TargetID_PR_NOTHING,	

	TargetID_PR_targetRANNodeID,
	TargetID_PR_targeteNB_ID,
	TargetID_PR_choice_Extensions
} TargetID_PR;



struct TargetRANNodeID;
struct TargeteNB_ID;
struct ProtocolIE_SingleContainer;



typedef struct TargetID {
	TargetID_PR present;
	union TargetID_u {
		struct TargetRANNodeID	*targetRANNodeID;
		struct TargeteNB_ID	*targeteNB_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} TargetID_t;



extern asn_TYPE_descriptor_t asn_DEF_TargetID;
extern asn_CHOICE_specifics_t asn_SPC_TargetID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargetID_1[3];
extern asn_per_constraints_t asn_PER_type_TargetID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
