/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_TargetNGRANNode_ToSourceNGRANNode_TransparentContainer_H_
#define	_TargetNGRANNode_ToSourceNGRANNode_TransparentContainer_H_


#include <asn_application.h>



#include "RRCContainer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct TargetNGRANNode_ToSourceNGRANNode_TransparentContainer {
	RRCContainer_t	 rRCContainer;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} TargetNGRANNode_ToSourceNGRANNode_TransparentContainer_t;



extern asn_TYPE_descriptor_t asn_DEF_TargetNGRANNode_ToSourceNGRANNode_TransparentContainer;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
