/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_TargeteNB_ID_H_
#define	_TargeteNB_ID_H_


#include <asn_application.h>



#include "GlobalNgENB-ID.h"
#include "EPS-TAI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct TargeteNB_ID {
	GlobalNgENB_ID_t	 globalENB_ID;
	EPS_TAI_t	 selected_EPS_TAI;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} TargeteNB_ID_t;



extern asn_TYPE_descriptor_t asn_DEF_TargeteNB_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_TargeteNB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_TargeteNB_ID_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
