/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_TNLAddressWeightFactor_H_
#define	_TNLAddressWeightFactor_H_


#include <asn_application.h>



#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef long	 TNLAddressWeightFactor_t;



extern asn_per_constraints_t asn_PER_type_TNLAddressWeightFactor_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TNLAddressWeightFactor;
asn_struct_free_f TNLAddressWeightFactor_free;
asn_struct_print_f TNLAddressWeightFactor_print;
asn_constr_check_f TNLAddressWeightFactor_constraint;
ber_type_decoder_f TNLAddressWeightFactor_decode_ber;
der_type_encoder_f TNLAddressWeightFactor_encode_der;
xer_type_decoder_f TNLAddressWeightFactor_decode_xer;
xer_type_encoder_f TNLAddressWeightFactor_encode_xer;
oer_type_decoder_f TNLAddressWeightFactor_decode_oer;
oer_type_encoder_f TNLAddressWeightFactor_encode_oer;
per_type_decoder_f TNLAddressWeightFactor_decode_uper;
per_type_encoder_f TNLAddressWeightFactor_encode_uper;
per_type_decoder_f TNLAddressWeightFactor_decode_aper;
per_type_encoder_f TNLAddressWeightFactor_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
