/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_TraceActivation_H_
#define	_TraceActivation_H_


#include <asn_application.h>



#include "NGRANTraceID.h"
#include "InterfacesToTrace.h"
#include "TraceDepth.h"
#include "TransportLayerAddress.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct TraceActivation {
	NGRANTraceID_t	 nGRANTraceID;
	InterfacesToTrace_t	 interfacesToTrace;
	TraceDepth_t	 traceDepth;
	TransportLayerAddress_t	 traceCollectionEntityIPAddress;
	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} TraceActivation_t;



extern asn_TYPE_descriptor_t asn_DEF_TraceActivation;
extern asn_SEQUENCE_specifics_t asn_SPC_TraceActivation_specs_1;
extern asn_TYPE_member_t asn_MBR_TraceActivation_1[5];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
