/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UE_NGAP_IDs_H_
#define	_UE_NGAP_IDs_H_


#include <asn_application.h>



#include "AMF-UE-NGAP-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum UE_NGAP_IDs_PR {
	UE_NGAP_IDs_PR_NOTHING,	

	UE_NGAP_IDs_PR_uE_NGAP_ID_pair,
	UE_NGAP_IDs_PR_aMF_UE_NGAP_ID,
	UE_NGAP_IDs_PR_choice_Extensions
} UE_NGAP_IDs_PR;



struct UE_NGAP_ID_pair;
struct ProtocolIE_SingleContainer;



typedef struct UE_NGAP_IDs {
	UE_NGAP_IDs_PR present;
	union UE_NGAP_IDs_u {
		struct UE_NGAP_ID_pair	*uE_NGAP_ID_pair;
		AMF_UE_NGAP_ID_t	 aMF_UE_NGAP_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} UE_NGAP_IDs_t;



extern asn_TYPE_descriptor_t asn_DEF_UE_NGAP_IDs;
extern asn_CHOICE_specifics_t asn_SPC_UE_NGAP_IDs_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_NGAP_IDs_1[3];
extern asn_per_constraints_t asn_PER_type_UE_NGAP_IDs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
