/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UEPagingIdentity_H_
#define	_UEPagingIdentity_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum UEPagingIdentity_PR {
	UEPagingIdentity_PR_NOTHING,	

	UEPagingIdentity_PR_fiveG_S_TMSI,
	UEPagingIdentity_PR_choice_Extensions
} UEPagingIdentity_PR;



struct FiveG_S_TMSI;
struct ProtocolIE_SingleContainer;



typedef struct UEPagingIdentity {
	UEPagingIdentity_PR present;
	union UEPagingIdentity_u {
		struct FiveG_S_TMSI	*fiveG_S_TMSI;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} UEPagingIdentity_t;



extern asn_TYPE_descriptor_t asn_DEF_UEPagingIdentity;
extern asn_CHOICE_specifics_t asn_SPC_UEPagingIdentity_specs_1;
extern asn_TYPE_member_t asn_MBR_UEPagingIdentity_1[2];
extern asn_per_constraints_t asn_PER_type_UEPagingIdentity_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
