/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UnavailableGUAMIItem_H_
#define	_UnavailableGUAMIItem_H_


#include <asn_application.h>



#include "GUAMI.h"
#include "TimerApproachForGUAMIRemoval.h"
#include "AMFName.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct ProtocolExtensionContainer;



typedef struct UnavailableGUAMIItem {
	GUAMI_t	 gUAMI;
	TimerApproachForGUAMIRemoval_t	*timerApproachForGUAMIRemoval;	

	AMFName_t	*backupAMFName;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} UnavailableGUAMIItem_t;



extern asn_TYPE_descriptor_t asn_DEF_UnavailableGUAMIItem;
extern asn_SEQUENCE_specifics_t asn_SPC_UnavailableGUAMIItem_specs_1;
extern asn_TYPE_member_t asn_MBR_UnavailableGUAMIItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
