/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_UserLocationInformation_H_
#define	_UserLocationInformation_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum UserLocationInformation_PR {
	UserLocationInformation_PR_NOTHING,	

	UserLocationInformation_PR_userLocationInformationEUTRA,
	UserLocationInformation_PR_userLocationInformationNR,
	UserLocationInformation_PR_userLocationInformationN3IWF,
	UserLocationInformation_PR_choice_Extensions
} UserLocationInformation_PR;



struct UserLocationInformationEUTRA;
struct UserLocationInformationNR;
struct UserLocationInformationN3IWF;
struct ProtocolIE_SingleContainer;



typedef struct UserLocationInformation {
	UserLocationInformation_PR present;
	union UserLocationInformation_u {
		struct UserLocationInformationEUTRA	*userLocationInformationEUTRA;
		struct UserLocationInformationNR	*userLocationInformationNR;
		struct UserLocationInformationN3IWF	*userLocationInformationN3IWF;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} UserLocationInformation_t;



extern asn_TYPE_descriptor_t asn_DEF_UserLocationInformation;
extern asn_CHOICE_specifics_t asn_SPC_UserLocationInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_UserLocationInformation_1[4];
extern asn_per_constraints_t asn_PER_type_UserLocationInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
