/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_WarningAreaList_H_
#define	_WarningAreaList_H_


#include <asn_application.h>



#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif



typedef enum WarningAreaList_PR {
	WarningAreaList_PR_NOTHING,	

	WarningAreaList_PR_eUTRA_CGIListForWarning,
	WarningAreaList_PR_nR_CGIListForWarning,
	WarningAreaList_PR_tAIListForWarning,
	WarningAreaList_PR_emergencyAreaIDList,
	WarningAreaList_PR_choice_Extensions
} WarningAreaList_PR;



struct EUTRA_CGIListForWarning;
struct NR_CGIListForWarning;
struct TAIListForWarning;
struct EmergencyAreaIDList;
struct ProtocolIE_SingleContainer;



typedef struct WarningAreaList {
	WarningAreaList_PR present;
	union WarningAreaList_u {
		struct EUTRA_CGIListForWarning	*eUTRA_CGIListForWarning;
		struct NR_CGIListForWarning	*nR_CGIListForWarning;
		struct TAIListForWarning	*tAIListForWarning;
		struct EmergencyAreaIDList	*emergencyAreaIDList;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	

	asn_struct_ctx_t _asn_ctx;
} WarningAreaList_t;



extern asn_TYPE_descriptor_t asn_DEF_WarningAreaList;
extern asn_CHOICE_specifics_t asn_SPC_WarningAreaList_specs_1;
extern asn_TYPE_member_t asn_MBR_WarningAreaList_1[5];
extern asn_per_constraints_t asn_PER_type_WarningAreaList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
