/*
 * Generated by asn1c-0.9.29 (http:
 * From ASN.1 module "NGAP-IEs"
 * 	found in "InformationElementDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -gen-PER`
 */

#ifndef	_XnExtTLA_Item_H_
#define	_XnExtTLA_Item_H_


#include <asn_application.h>



#include "TransportLayerAddress.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif



struct XnGTP_TLAs;
struct ProtocolExtensionContainer;



typedef struct XnExtTLA_Item {
	TransportLayerAddress_t	*iPsecTLA;	

	struct XnGTP_TLAs	*gTP_TLAs;	

	struct ProtocolExtensionContainer	*iE_Extensions;	

	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	

	asn_struct_ctx_t _asn_ctx;
} XnExtTLA_Item_t;



extern asn_TYPE_descriptor_t asn_DEF_XnExtTLA_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_XnExtTLA_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_XnExtTLA_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	

#include <asn_internal.h>
