$(DEPS_DIR)/NF_A_linking.o: NF_A_linking.cpp | $(DEPS_DIR)
	@$(CC) $(CFLAGS) -c NF_A_linking.cpp -o $(DEPS_DIR)/NF_A_linking.o

$(DEPS_DIR)/platform.o: NF_A_platform.cpp | $(DEPS_DIR)
	@$(CC) $(CFLAGS) -c NF_A_platform.cpp -o $(DEPS_DIR)/platform.o

$(DEPS_DIR)/udf.o: ../../udf.cpp | $(DEPS_DIR)
	@$(CC) $(CFLAGS) -c ../../udf.cpp -o $(DEPS_DIR)/udf.o

$(DEPS_DIR)/logging.o: $(LOG_LIB_DIR)/logging.cpp | $(DEPS_DIR)
	@$(CC) $(CFLAGS) -c $(LOG_LIB_DIR)/logging.cpp -o $(DEPS_DIR)/logging.o

$(DEPS_DIR):
	mkdir -p $(DEPS_DIR)

clean:
	rm -rf $(BUILD_DIR)

.PHONY: clean

